server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: aidar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG