server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**
              Path=/api/claims/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true